# Generated by Django 4.1.4 on 2024-10-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_alter_transaction_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='rsrv1',
            field=models.CharField(blank=True, help_text='Max number of connection failures of incommunication before this is reported as a processerror (default: direct report).', max_length=35, null=True, verbose_name='Max failures'),
        ),
    ]
