#Generated by bots open source edi translator from UN-docs.
from bots.utils.botsconfig import *
from bots.usersys.grammars.edifact.edifact import syntax
from bots.usersys.grammars.edifact.recordsD96AUN import recorddefs


structure = \
    [
    {
        ID: 'UNH',
        MIN: 1,
        MAX: 9,
        QUERIES: {
    
        },
        SUBTRANSLATION: [
    
        ],
        LEVEL: [
        {
            ID: 'BGM',
            MIN: 1,
            MAX: 1,
            LEVEL: [
    
            ],
        },
        {
            ID: 'DTM',
            MIN: 0,
            MAX: 10,
            LEVEL: [
    
            ],
        },
        {
            ID: 'ALI',
            MIN: 0,
            MAX: 5,
            LEVEL: [
    
            ],
        },
        {
            ID: 'MEA',
            MIN: 0,
            MAX: 5,
            LEVEL: [
    
            ],
        },
        {
            ID: 'MOA',
            MIN: 0,
            MAX: 5,
            LEVEL: [
    
            ],
        },
        {
            ID: 'RFF',
            MIN: 0,
            MAX: 10,
            LEVEL: [
            {
                ID: 'DTM',
                MIN: 0,
                MAX: 1,
                LEVEL: [
    
                ],
            }
            ],
        },
        {
            ID: 'NAD',
            MIN: 0,
            MAX: 10,
            LEVEL: [
            {
                ID: 'LOC',
                MIN: 0,
                MAX: 10,
                LEVEL: [
    
                ],
            },
            {
                ID: 'RFF',
                MIN: 0,
                MAX: 10,
                LEVEL: [
                {
                    ID: 'DTM',
                    MIN: 0,
                    MAX: 1,
                    LEVEL: [
    
                    ],
                }
                ],
            },
            {
                ID: 'CTA',
                MIN: 0,
                MAX: 10,
                LEVEL: [
                {
                    ID: 'COM',
                    MIN: 0,
                    MAX: 5,
                    LEVEL: [
    
                    ],
                }
                ],
            }
            ],
        },
        {
            ID: 'TOD',
            MIN: 0,
            MAX: 10,
            LEVEL: [
            {
                ID: 'LOC',
                MIN: 0,
                MAX: 5,
                LEVEL: [
    
                ],
            },
            {
                ID: 'FTX',
                MIN: 0,
                MAX: 5,
                LEVEL: [
    
                ],
            }
            ],
        },
        {
            ID: 'TDT',
            MIN: 0,
            MAX: 10,
            LEVEL: [
            {
                ID: 'PCD',
                MIN: 0,
                MAX: 6,
                LEVEL: [
    
                ],
            },
            {
                ID: 'LOC',
                MIN: 0,
                MAX: 10,
                LEVEL: [
                {
                    ID: 'DTM',
                    MIN: 0,
                    MAX: 10,
                    LEVEL: [
    
                    ],
                }
                ],
            }
            ],
        },
        {
            ID: 'EQD',
            MIN: 0,
            MAX: 10,
            LEVEL: [
            {
                ID: 'MEA',
                MIN: 0,
                MAX: 5,
                LEVEL: [
    
                ],
            },
            {
                ID: 'SEL',
                MIN: 0,
                MAX: 25,
                LEVEL: [
    
                ],
            },
            {
                ID: 'EQA',
                MIN: 0,
                MAX: 5,
                LEVEL: [
    
                ],
            },
            {
                ID: 'HAN',
                MIN: 0,
                MAX: 10,
                LEVEL: [
                {
                    ID: 'FTX',
                    MIN: 0,
                    MAX: 10,
                    LEVEL: [
    
                    ],
                }
                ],
            }
            ],
        },
        {
            ID: 'CPS',
            MIN: 0,
            MAX: 9999,
            LEVEL: [
            {
                ID: 'FTX',
                MIN: 0,
                MAX: 5,
                LEVEL: [
    
                ],
            },
            {
                ID: 'PAC',
                MIN: 0,
                MAX: 9999,
                LEVEL: [
                {
                    ID: 'MEA',
                    MIN: 0,
                    MAX: 10,
                    LEVEL: [
    
                    ],
                },
                {
                    ID: 'QTY',
                    MIN: 0,
                    MAX: 10,
                    LEVEL: [
    
                    ],
                },
                {
                    ID: 'HAN',
                    MIN: 0,
                    MAX: 10,
                    LEVEL: [
                    {
                        ID: 'FTX',
                        MIN: 0,
                        MAX: 10,
                        LEVEL: [
    
                        ],
                    }
                    ],
                },
                {
                    ID: 'PCI',
                    MIN: 0,
                    MAX: 1000,
                    LEVEL: [
                    {
                        ID: 'RFF',
                        MIN: 0,
                        MAX: 1,
                        LEVEL: [
    
                        ],
                    },
                    {
                        ID: 'DTM',
                        MIN: 0,
                        MAX: 5,
                        LEVEL: [
    
                        ],
                    },
                    {
                        ID: 'GIR',
                        MIN: 0,
                        MAX: 99,
                        LEVEL: [
    
                        ],
                    },
                    {
                        ID: 'GIN',
                        MIN: 0,
                        MAX: 99,
                        LEVEL: [
                        {
                            ID: 'DLM',
                            MIN: 0,
                            MAX: 10,
                            LEVEL: [
    
                            ],
                        }
                        ],
                    }
                    ],
                }
                ],
            },
            {
                ID: 'LIN',
                MIN: 0,
                MAX: 9999,
                LEVEL: [
                {
                    ID: 'PIA',
                    MIN: 0,
                    MAX: 10,
                    LEVEL: [
    
                    ],
                },
                {
                    ID: 'IMD',
                    MIN: 0,
                    MAX: 25,
                    LEVEL: [
    
                    ],
                },
                {
                    ID: 'MEA',
                    MIN: 0,
                    MAX: 10,
                    LEVEL: [
    
                    ],
                },
                {
                    ID: 'QTY',
                    MIN: 0,
                    MAX: 10,
                    LEVEL: [
    
                    ],
                },
                {
                    ID: 'ALI',
                    MIN: 0,
                    MAX: 10,
                    LEVEL: [
    
                    ],
                },
                {
                    ID: 'GIN',
                    MIN: 0,
                    MAX: 100,
                    LEVEL: [
    
                    ],
                },
                {
                    ID: 'GIR',
                    MIN: 0,
                    MAX: 100,
                    LEVEL: [
    
                    ],
                },
                {
                    ID: 'DLM',
                    MIN: 0,
                    MAX: 100,
                    LEVEL: [
    
                    ],
                },
                {
                    ID: 'DTM',
                    MIN: 0,
                    MAX: 5,
                    LEVEL: [
    
                    ],
                },
                {
                    ID: 'FTX',
                    MIN: 0,
                    MAX: 5,
                    LEVEL: [
    
                    ],
                },
                {
                    ID: 'MOA',
                    MIN: 0,
                    MAX: 5,
                    LEVEL: [
    
                    ],
                },
                {
                    ID: 'RFF',
                    MIN: 0,
                    MAX: 10,
                    LEVEL: [
                    {
                        ID: 'DTM',
                        MIN: 0,
                        MAX: 1,
                        LEVEL: [
    
                        ],
                    }
                    ],
                },
                {
                    ID: 'DGS',
                    MIN: 0,
                    MAX: 10,
                    LEVEL: [
                    {
                        ID: 'QTY',
                        MIN: 0,
                        MAX: 1,
                        LEVEL: [
    
                        ],
                    },
                    {
                        ID: 'FTX',
                        MIN: 0,
                        MAX: 5,
                        LEVEL: [
    
                        ],
                    }
                    ],
                },
                {
                    ID: 'LOC',
                    MIN: 0,
                    MAX: 100,
                    LEVEL: [
                    {
                        ID: 'NAD',
                        MIN: 0,
                        MAX: 1,
                        LEVEL: [
    
                        ],
                    },
                    {
                        ID: 'DTM',
                        MIN: 0,
                        MAX: 1,
                        LEVEL: [
    
                        ],
                    },
                    {
                        ID: 'QTY',
                        MIN: 0,
                        MAX: 10,
                        LEVEL: [
    
                        ],
                    }
                    ],
                },
                {
                    ID: 'SGP',
                    MIN: 0,
                    MAX: 1000,
                    LEVEL: [
                    {
                        ID: 'QTY',
                        MIN: 0,
                        MAX: 10,
                        LEVEL: [
    
                        ],
                    }
                    ],
                },
                {
                    ID: 'PCI',
                    MIN: 0,
                    MAX: 9999,
                    LEVEL: [
                    {
                        ID: 'DTM',
                        MIN: 0,
                        MAX: 5,
                        LEVEL: [
    
                        ],
                    },
                    {
                        ID: 'MEA',
                        MIN: 0,
                        MAX: 10,
                        LEVEL: [
    
                        ],
                    },
                    {
                        ID: 'QTY',
                        MIN: 0,
                        MAX: 1,
                        LEVEL: [
    
                        ],
                    },
                    {
                        ID: 'GIN',
                        MIN: 0,
                        MAX: 10,
                        LEVEL: [
                        {
                            ID: 'DLM',
                            MIN: 0,
                            MAX: 100,
                            LEVEL: [
    
                            ],
                        }
                        ],
                    },
                    {
                        ID: 'HAN',
                        MIN: 0,
                        MAX: 10,
                        LEVEL: [
                        {
                            ID: 'FTX',
                            MIN: 0,
                            MAX: 5,
                            LEVEL: [
    
                            ],
                        },
                        {
                            ID: 'GIN',
                            MIN: 0,
                            MAX: 1000,
                            LEVEL: [
    
                            ],
                        }
                        ],
                    }
                    ],
                },
                {
                    ID: 'QVR',
                    MIN: 0,
                    MAX: 10,
                    LEVEL: [
                    {
                        ID: 'DTM',
                        MIN: 0,
                        MAX: 5,
                        LEVEL: [
    
                        ],
                    }
                    ],
                }
                ],
            }
            ],
        },
        {
            ID: 'CNT',
            MIN: 0,
            MAX: 5,
            LEVEL: [
    
            ],
        },
        {
            ID: 'UNT',
            MIN: 1,
            MAX: 1,
            LEVEL: [
    
            ],
        }
        ],
    }
    ]
