# Generated by Django 4.1.4 on 2023-03-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammarview', '0002_grammarrecord_bformat_grammarrecord_decimals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarrecord',
            name='botsidnr',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='grammarrecord',
            name='count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='grammarrecord',
            name='fixedrecordlength',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='grammarrecord',
            name='max',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='grammarrecord',
            name='min',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='grammarrecord',
            name='subtranslation',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
